### ISSUE TITLE
🐛当title或name 以 “...” 结尾时，会出现不能继续下载的情况

### ISSUE THREAD

**Issue by TinyRei** [SigureMo/yutto#16]
### 问题简述

**BUG1**、当文件夹名(title) 或 文件名(name)  以 “...” 结尾，即文件名结尾含多个点时，会出现不能继续下载文件的情况。
用以下视频下载时可复现：
https://www.bilibili.com/video/BV1mW41197jh?from=search&seid=16535887961016164275&spm_id_from=333.337.0.0

**BUG2**、SESSDATA错误时建议直接挂起或拒绝继续下载。
SESSDATA容易过期，如果含SESSDATA且失效，建议直接拒绝下载，因为部分资源现在清晰度不够或是资源下载不全。
（我习惯作为脚本爬取资源，如果SESSDATA失效建议直接挂起，便于维护）

### 复现方式

----BUG1----
复现方式：`yutto “https://www.bilibili.com/video/BV1mW41197jh?from=search&seid=16535887961016164275&spm_id_from=333.337.0.0”`

### 环境信息

-  OS: win10
-  Python: Python 3.9.5
-  yutto: yutto 2.0.0-beta.4

**Comment by SigureMo** [comment]
问题 1：

在 macOS 与 Windows 均无法复现，请提供详细报错信息

问题 2：

已经有是否以大会员登陆的提示信息，而且我不会拒绝非大会员下载视频。

这些需求都是一些特殊需求，放在 issue 里不太合适吧？
