### ISSUE TITLE
🐛 当下载具有特定视频的收藏夹时, 出现抓取超时

### ISSUE THREAD

**Issue by ptable-1** [SigureMo/yutto#59]
### 问题简述

当下载收藏夹的时候, stdout 出现大规模的

```
 WARN  抓取超时，正在重试，剩余 2 次
``` 

并且最终重试失败,程序退出.

而对收藏夹内视频单独进行下载时, 没有问题出现

### 复现方式

收藏夹有3个视频
1. https://www.bilibili.com/video/BV1Xt411f7Pc
2. https://www.bilibili.com/video/BV1FU4y177Cs
3. https://www.bilibili.com/video/BV1Gx411w7wU

合计大约有 774 p 视频

```
yutto -b <收藏夹url> -n 16 --proxy "no"  -c "cookies非大会员" --no-danmaku
```

### 环境信息

-  OS: 版本	Windows 11 教育版 21H2 22000.526
-  Python: 3.10.2
-  yutto: 2.0.0-beta.10
-  FFmpeg:  5.0-full_build-www.gyan.dev
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/SigureMo/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/SigureMo/yutto/issues) 和 [discussion](https://github.com/SigureMo/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
啊，这第三个视频有点离谱了啊 662P，解析时候会发出大量的请求导致短暂封掉 IP，这个问题我近期再复查一下吧

**Comment by SigureMo** [comment]
唔，#60 应该是把大量重复请求的问题解决了，现在我这能成功解析 774p 进入到下载状态。

虽然当时能解析完，但马上再尝试下载别的时候发现还是被封了……唔，请求数量还是太多了……

**Comment by WhileKing** [comment]
> 唔，#60 应该是把大量重复请求的问题解决了，现在我这能成功解析 774p 进入到下载状态。
> 
> 虽然当时能解析完，但马上再尝试下载别的时候发现还是被封了……唔，请求数量还是太多了……

是不是可以考虑逐个下载的支持？像这种这么大的

**Comment by SigureMo** [comment]
> 是不是可以考虑逐个下载的支持？像这种这么大的

emmm，看到这个我也考虑了下，但这区别只是短时间 774 * (字幕 + ~~弹幕~~ + 音视频)条请求 和 短时间 662 * (字幕 + ~~弹幕~~ + 音视频)条请求的区别，其实感觉差别不大，应该还是会被封……

唔，要么就把所有请求延迟到下载前一刻？这样每经过一次下载之后会请求 （字幕 + ~~弹幕~~ + 音视频) 才三条，感觉被封的可能性会小很多，但是可能改起来稍微麻烦些……

**Comment by SigureMo** [comment]
刚刚在 #61 将链接解析（字幕、弹幕、音视频 url）完全推迟到下在前一刻了，看起来能 work，我再测试一下就发个新版本吧～

**Comment by SigureMo** [comment]
刚刚发布了 2.0.0-beta.11，可以试一下～按理说应该不会有那个问题了，如果有问题的话可以 reopen～

**Comment by WhileKing** [comment]
> > 是不是可以考虑逐个下载的支持？像这种这么大的
> 
> emmm，看到这个我也考虑了下，但对于这个收藏夹的话，区别只是短时间 774 * (字幕 + ~弹幕~ + 音视频)条请求 和 短时间 662 * (字幕 + ~弹幕~ + 音视频)条请求的区别，其实感觉差别不大，应该还是会被封……
> 
> 唔，要么就把所有请求延迟到下载前一刻？这样每经过一次下载之后会请求 （字幕 + ~弹幕~ + 音视频) 才三条，感觉被封的可能性会小很多，但是可能改起来稍微麻烦些……

嗯嗯，我的意思就是推迟到下载前的那一刻，774p，一次下载只有三条请求，下完才下一p。
