### ISSUE TITLE
✨ 可以把FFmpeg加入编译好的文件夹里

### ISSUE THREAD

**Issue by BoxuanZng** [SigureMo/yutto#7]
### 特性描述

可以把FFmpeg加入编译好的文件夹里，这样就可以不需要下载FFmpeg也能下载视频、番剧.....

### 建议解决方案

编译好Yutto之后，将FFmpeg的EXE可执行文件和Yutto的可执行文件放到一个目录，然后打包成压缩包文件，之后再上传Github

**Comment by SigureMo** [comment]
可是这本质上还是下载啊……而且我需要打包所有平台的包……
